# Generated by Django 5.2.6 on 2025-09-03 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_direccion_detalles_biblioteca_lector_libro_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
