# Generated by Django 5.2.6 on 2025-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0003_autor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
