# Generated by Django 5.2.6 on 2025-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0005_categoria_tipocategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
