# Generated by Django 5.2.7 on 2025-10-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0006_alter_lector_rut_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='web',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='correo_lector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.categoria'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_retorno',
            field=models.DateTimeField(blank=True),
        ),
    ]
