# Generated by Django 5.2.8 on 2025-11-05 20:28

import datetime
import primera_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0007_alter_autor_biografia_alter_autor_id_nacionalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), validators=[primera_app.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nombre_lector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[primera_app.models.validar_rut]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
